# Generated by Django 4.2.6 on 2023-12-10 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userprofile_options_alter_userprofile_role_and_more'),
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemlog',
            options={'verbose_name': 'System log', 'verbose_name_plural': 'System logs'},
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='action',
            field=models.CharField(verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='log_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Log time'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='userprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.userprofile', verbose_name='User Profile'),
        ),
    ]
