# Generated by Django 4.2.6 on 2023-12-10 15:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_options_alter_category_name_and_more'),
        ('authentication', '0002_alter_userprofile_options_alter_userprofile_role_and_more'),
        ('payments', '0002_alter_payment_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'verbose_name': 'Payment history', 'verbose_name_plural': 'Payment histories'},
        ),
        migrations.AlterModelOptions(
            name='paymenttemplate',
            options={'verbose_name': 'Payment template', 'verbose_name_plural': 'Payment templates'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_prev_amount',
            field=models.BooleanField(default=False, verbose_name='Prev Amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Payment time'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payments.payment', verbose_name='Payment'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Payment time'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='prev_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Prev amount'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='price_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Price amount'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='payments.paymenttemplate', verbose_name='Payment template'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='userprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.userprofile', verbose_name='User Profile'),
        ),
        migrations.AlterField(
            model_name='paymenttemplate',
            name='name',
            field=models.CharField(verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='paymenttemplate',
            name='userprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.userprofile', verbose_name='User Profile'),
        ),
    ]
