# Generated by Django 4.2.6 on 2023-11-23 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_photo", models.ImageField(upload_to="documents/")),
                ("birth_date", models.DateField(blank=True, default=None, null=True)),
                ("country", models.CharField(blank=True, default=None, null=True)),
                ("id_number", models.CharField(blank=True, default=None, null=True)),
                (
                    "userprofile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="authentication.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "documents",
            },
        ),
    ]
