# Generated by Django 4.2.6 on 2023-12-10 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userprofile_options_alter_userprofile_role_and_more'),
        ('documents', '0002_alter_document_country_alter_document_id_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterField(
            model_name='document',
            name='birth_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='document',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_photo',
            field=models.ImageField(upload_to='documents/', verbose_name='Document photo'),
        ),
        migrations.AlterField(
            model_name='document',
            name='id_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Id number'),
        ),
        migrations.AlterField(
            model_name='document',
            name='userprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.userprofile', verbose_name='User Profile'),
        ),
    ]
