# Generated by Django 4.2.6 on 2023-12-10 15:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_options_alter_document_birth_date_and_more'),
        ('authentication', '0002_alter_userprofile_options_alter_userprofile_role_and_more'),
        ('credits', '0002_alter_creditrequest_approved_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditrequest',
            options={'verbose_name': 'Credit', 'verbose_name_plural': 'Credits'},
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Approved amount'),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='documents.document', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='request_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Request amount'),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='userprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.userprofile', verbose_name='User Profile'),
        ),
    ]
